name: Deploy Project
on: push
jobs: 
    deploying:
        runs-on: macos-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v3
            -   name: Install
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install dependencies
                run: npm ci
            -   name: Run lint
                run: |
                    npm run lint
                    npm test
                    npm run build
                    echo "deploy finished... yay"
                